var v=Object.defineProperty;var A=Object.getOwnPropertyDescriptor;var F=Object.getOwnPropertyNames;var M=Object.prototype.hasOwnProperty;var G=(s,i)=>{for(var t in i)v(s,t,{get:i[t],enumerable:!0})},W=(s,i,t,e)=>{if(i&&typeof i=="object"||typeof i=="function")for(let n of F(i))!M.call(s,n)&&n!==t&&v(s,n,{get:()=>i[n],enumerable:!(e=A(i,n))||e.enumerable});return s};var x=s=>W(v({},"__esModule",{value:!0}),s);var q={};G(q,{default:()=>g});module.exports=x(q);var T=require("obsidian"),R=/^(?:\s*)(?:[-*+]|\d+\.)\s/,P=/^(?:\s*)(?:[-*+]|\d+\.)\s\[[xX]\]/,$=/^(?:\s*)(?:[-*+]|\d+\.)\s\[[ xX]\]/,D=/^(\s*)/,j=5e3,S="\0",y=5;function f(s){return D.exec(s)[1].length}function b(s){return R.test(s)}function u(s){return P.test(s)}function N(s){let i=new Array(s.length).fill(!1),t=!1;for(let e=0;e<s.length;e++)s[e].trimStart().startsWith("```")&&(t=!t),i[e]=t;return i}function O(s,i,t){if(i[t])return[t,t];let e=t;for(;e>0&&!i[e-1]&&b(s[e-1]);)e--;let n=t;for(;n<s.length-1&&!i[n+1]&&b(s[n+1]);)n++;return[e,n]}function Y(s,i){let t=[],e=null;for(let n of s)f(n)===i&&b(n)?(e&&t.push(e),e={lines:[n],completed:u(n)}):e?e.lines.push(n):t.push({lines:[n],completed:!1});return e&&t.push(e),t}function B(s){let i=s.filter(e=>!e.completed),t=s.filter(e=>e.completed);return[...i,...t]}function K(s,i){let t=f(s[i]),e=i;for(;e>0&&f(s[e-1])>=t;)e--;let n=i;for(;n<s.length-1&&f(s[n+1])>=t;)n++;return[e,n]}function X(s,i){let t=s.split(`
`),e=N(t),[n,o]=O(t,e,i),r=t.slice(n,o+1),c=i-n,l=f(r[c]),[p,h]=K(r,c),a=r.slice(p,h+1),d=Y(a,l),m=B(d),C=a.join(`
`),w=m.flatMap(_=>_.lines).join(`
`);if(C===w)return null;let E=n+p,L=n+h,k=w.split(`
`);return t.splice(E,L-E+1,...k),t.join(`
`)}function H(s,i,t){if(i<s.length&&s[i]===t)return i;let e=Math.max(0,i-y),n=Math.min(s.length-1,i+y);for(let o=e;o<=n;o++)if(s[o]===t)return o;for(let o=e;o<=n;o++)if(u(s[o]))return o;return-1}var g=class extends T.Plugin{constructor(){super(...arguments);this.pendingTimers=new Map;this.contentCache=new Map;this.ownWrites=new Set}onload(){this.registerEvent(this.app.vault.on("modify",t=>{!(t instanceof T.TFile)||t.extension!=="md"||this.handleFileModify(t)})),this.registerEvent(this.app.workspace.on("file-open",t=>{!t||t.extension!=="md"||this.app.vault.read(t).then(e=>{this.contentCache.set(t.path,e)})}))}onunload(){for(let{timer:t}of this.pendingTimers.values())clearTimeout(t);this.pendingTimers.clear(),this.contentCache.clear(),this.ownWrites.clear()}async handleFileModify(t){var l,p,h;if(this.ownWrites.has(t.path)){this.ownWrites.delete(t.path);return}let e=await this.app.vault.read(t),n=(l=this.contentCache.get(t.path))!=null?l:"";if(e===n)return;this.contentCache.set(t.path,e);let o=n.split(`
`),r=e.split(`
`),c=Math.max(o.length,r.length);for(let a=0;a<c;a++){let d=(p=o[a])!=null?p:"",m=(h=r[a])!=null?h:"";$.test(d)&&u(m)&&!u(d)?this.scheduleSort(t,a,m):u(d)&&!u(m)&&this.cancelTimer(t.path,a)}}scheduleSort(t,e,n){let o=`${t.path}${S}${e}`,r=this.pendingTimers.get(o);r!==void 0&&clearTimeout(r.timer);let c=setTimeout(()=>{this.pendingTimers.delete(o),this.executeSort(t,e,n)},j);this.pendingTimers.set(o,{timer:c,lineContent:n})}cancelTimer(t,e){let n=`${t}${S}${e}`,o=this.pendingTimers.get(n);o!==void 0&&(clearTimeout(o.timer),this.pendingTimers.delete(n))}async executeSort(t,e,n){let o=await this.app.vault.read(t),r=o.split(`
`),c=H(r,e,n);if(c===-1||!u(r[c]))return;let l=X(o,c);l!==null&&(this.ownWrites.add(t.path),this.contentCache.set(t.path,l),await this.app.vault.modify(t,l))}};
